export const MOVIE_TITLE = 'MOVIE_TITLE';
export const SEARCH_MOVIES_REQUEST = 'SEARCH_MOVIES_REQUEST';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE'; 
export const GET_MOVIE_BY_ID = 'GET_MOVIE_BY_ID';
export const RESET_MOVIE = 'RESET_MOVIE';